name: Laravel Pint

on:
    push:
      branches:
        - main
jobs:
    laravel-pint:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: shivammathur/setup-php@v2
        # uses: ./.github/actions/setup
        with:
         php-version: '8.4'
         tools: composer:v2
         #coverage: none
         #extensions: 'json, dom, curl, libxml, mbstring'
          #nova-email: ${{ secrets.NOVA_EMAIL }}
          #nova-password: ${{ secrets.NOVA_PASSWORD }}

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: ~/.composer/vendor/bin/pint
        # run: pint

      - name: Push Changes Back to Repo
        run: |
          git config user.name "gh-actions"
          git config user.email "gh@laracasts.com"
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push
